# The main configuration file for Prometheus

global:
  scrape_interval: 15s # How often Prometheus will scrape metrics

scrape_configs:
  - job_name: 'smart-home-services'
    static_configs:
      - targets: ['device-management-service:8081', 'user-management-service:8082']

  - job_name: 'device-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['device-management-service:8081']
