{
 "title": "my_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Number of active devices in Smart Home - my custom gauge metric",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_devices", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of published messages (RabbitMQ)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 8, "y": 0 },
   "targets": [
    { "expr": "rabbitmq_published_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Check if services are up or down",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 17 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 17 },
   "targets": [
    { "expr": "process_cpu_time_ns_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 16, "x": 0, "y": 29 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}